apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
      - name: be-app
        image: devbhutani10/sample-cicd:4afc1c029aec633ee2a7b711483ea640a7f38b70
        ports:
        - containerPort: 3000
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_URL
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
  namespace: default
spec:
  selector:
    app: be-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP