---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    DB_URL: AgA+JNwICjzQX0T6wtUZSD9yYwJG+NlU02xo1udPu5XVLm4dm4bMeBwIonX9Ij/N3A+CQfEPZvsluCDwasgQoc2UGW2YhI3NCMDrmgtlmJp8MCKB1mnrfMirz0izPypiSEDGOoLQprvJitZzkW6QO8JCmbZmeT8O/FnKkvSXXBZnEbiWx639RZtOsdsSOppRENz0fxazwgDvPgKX4GrGYYOOh7yeqKepp021C+EbO8qB+wyMscIaeCMPmYv+dh7eG2lwHriusgsUiFo92AwwmvTZgyK3ruqmpyIl8EoWbrvMYKJPbNYQ7OzMeQuyyZdpZEf6QKBQYc2JyR7au0T3vQLQjSqPtgCR/IIIB+J4uNRvyL2gQzn6JlN4Va75tQiGLH37ofkqdqzX4HIzefD/hkBjoQLt/vIE8AKbyBT0XPbjXoQ1gUSGsno1FCuO5gLr/1oLXutBj31sArkl0RclerhH9N8D5Zgtc+WMgHLJDvi6Otfex7BED4cSbGs3QZ05LSkLlyFEYP/J6UfoI5youTrJZWk3ovQvZMt9MCelGIzq4EWGY2fata4Vyw7ogpasY/UDoS5SYsxXycPf6XnfYSk43qxcPsZdMHmEUcx2/x5JLtE95Vx7Xo+4nHglMowDGNerLct4rEBTtX9AsW9guGzINzxsxRXTOmDT4aenW346YJaxrAX3aSKEJqgn766nKA51EsWaaf4OWePyFCAFXv5ElA8H
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: default
